require_relative 'coverage/version'
require_relative 'coverage/config'
require_relative 'coverage/continuous_build'
require_relative 'coverage/git'
require_relative 'coverage/client_api'
require_relative 'coverage/formatter'
